<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ErrorHandler\Module'                        => __DIR__ . '/Module.php',
    'ErrorHandler\Controller\ErrorHandlerController' => __DIR__ . '/src/ErrorHandler/Controller/ErrorHandlerController.php',
    'ErrorHandlerTest\Framework\TestCase'        => __DIR__ . '/tests/ErrorHandler/Framework/TestCase.php',
    'ErrorHandlerTest\SampleTest'                => __DIR__ . '/tests/ErrorHandler/SampleTest.php',
);
